.TH debtakeover 1 2005-07-31 0.8 "debtakeover's manual"
.\"
.\" $Id$
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
debtakeover \- replace in runtime a system to Debian
.SH SYNOPSIS
.B debtakeover
.RI [ options ]
.SH DESCRIPTION
The \fBdebtakeover\fP utility is used to replace the current running system to
Debian. Its main purpose is to be used on a colocated server, where you do not
have physical access to the host.
.SH OPTIONS
.TP
.BI \-\-profile= string
Installation profile (default "\fIcolo\fP"). Set it to "\fInone\fP" to disable.
.TP
.BI \-\-suite= string
Debian suite (default "\fIwoody\fP"). Right now the only supported suite is
\fIwoody\fP, if you use any other suite it may break.
.TP
.BI \-\-mirror= url
Debian mirror (default "\fIhttp://ftp.no.debian.org/\fP").
.TP
.BI \-\-tarball= file
Debian base tarball to use instead of generating one with debootstrap. It
supports compressed tarballs with gzip, bzip2 and compress.
.TP
.BI \-\-debootstrap= path
Debootstrap compatible binary (default "\fIdebootstrap\fP"). Other alternatives
that may not work are \fBcdebootstrap\fP and \fBcrosshurd\fP.
.TP
.BI \-\-debootstrap\-args= string
Debootstrap extra arguments.
.TP
.B \-\-force\-purify
Force the purification (non-interactive). Do not ask for confirmation.
.TP
.B \-\-force\-retakeover
Force taking over a Debian system. Useful when converting derived Debian
distros or to reinstall a system from scratch.
.TP
.B \-\-verbose
Be more verbose. This only afects the output to the terminal, the logs retain
all important information.
.TP
.B \-\-version
Print program version.
.TP
.B \-\-help
Print this help.
.SH SEE ALSO
.BR debootstrap (1).
.SH AUTHOR
This manual page was written by Guillem Jover <guillem@debian.org>.
